#Standard footprint
footprint_topic: /nav_3d/robot_footprint
#published_footprint_topic: /nav_3d/robot_footprint

#robot_base_frame: base_link
robot_base_frame: base_link
update_frequency: 1.0
publish_frequency: 6.0
transform_tolerance: 5.0

resolution: 0.03

obstacle_range: 5.5
raytrace_range: 6.0
observation_persistence: 0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: /nav_3d/live_scan, inf_is_valid: true}

inflation:
    inflation_radius: 0.05
