#Standard footprint
#footprint: [[-0.55, -0.35], [-0.55, 0.35], [0.16, 0.49], [0.57, 0.35], [0.57, -0.35], [0.1, -0.47]]

#Temoto footprint
footprint: [[-0.55, -0.35], [-0.55, 0.35], [0.57, 0.35], [0.57, -0.35], [0.27,-0.68], [-0.16,-0.68]]


footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 5.0

resolution: 0.02

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: /lidar/scan, inf_is_valid: true}

inflation:
    inflation_radius: 0.4
