map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: odom

two_d_mode: false

frequency: 50

#odom0: husky_velocity_controller/odom
odom0: nrg_nav_filter/odom

odom0_config: [false, false, false,
               false, false, false,
               true, true, true,
               false, false, true,
               false, false, false]
odom0_differential: false
#odom0_relative: false

odom0_queue_size: 10

#imu0: imu/data
imu0: nrg_nav_filter/imu
imu0_config: [true, true, true,
              true, true, true,
              true, true, true,
              true, true, true,
              false, false, false]
imu0_differential: false
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: false
