teleop_twist_joy:
  axis_linear: 1
  scale_linear: 0.4
  scale_linear_turbo: 0.6
  axis_angular: 0
  scale_angular: 0.12
  scale_angular_turbo: 0.15
  enable_button: 0
  enable_turbo_button: 0
joy_node: 
  deadzone: 0.1
  autorepeat_rate: 20
teleop_ur_joy:
  longitudinal_axis: 7
  lateral_axis: 6
  trans_rot_toggle: 2
  preset1_button: 3
  preset2_button: 1
  linear_velocity: 0.1
  rotational_velocity: 0.02
  acceleration: 0.01
