topics:
- name    : joy #Xbox
  topic   : joy_teleop/cmd_vel
  timeout : 0.5
  priority: 10
- name    : joy_console #Xbox
  topic   : joy_teleop_console/cmd_vel
  timeout : 0.5
  priority: 9
- name    : temoto
  topic   : temoto/base_cmd_vel
  timeout : 0.5
  priority: 8
- name    : interactive_marker
  topic   : twist_marker_server/cmd_vel
  timeout : 0.5
  priority: 7
- name    : move_base #autonomy
  topic   : move_base/cmd_vel
  timeout : 0.5
  priority: 2
- name    : external
  topic   : cmd_vel
  timeout : 0.5
  priority: 1

locks:
- name    : e_stop
  topic   : e_stop
  timeout : 0.0    
  priority: 255
